# MODEL

In [3]:
import pandas as pd

df = pd.read_csv("C:\Makine Öğrenmesi-2\Advertising.csv")
df = df.iloc[: , 1:len(df)]
df.head()

<>:3: SyntaxWarning: invalid escape sequence '\M'
<>:3: SyntaxWarning: invalid escape sequence '\M'
C:\Users\BedirhanOrseloglu\AppData\Local\Temp\ipykernel_18644\2197433482.py:3: SyntaxWarning: invalid escape sequence '\M'
  df = pd.read_csv("C:\Makine Öğrenmesi-2\Advertising.csv")

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
x = df.drop("sales" , axis=1)
y = df[["sales"]]   #çift tırnak yazmamın sebebi dataframe olarak görüntülemek

In [5]:
x.head()

      TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [6]:
y.head()

   sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

    Modellemek için iki farklı yöntemimiz olacak:
- Statsmodel ile model -> katsayılar kısmıyla ilgili modelleme
- Scikitlearn ile model

# Statsmodel İle Model Kurmak

In [12]:
import statsmodels.api as sm

lm = sm.OLS(y , x)      # lm = lineer model ; OLS = regresyon modelini kurmak için gerekli fonks (içine önce bağımlı sonra bağımsız değişken)

In [13]:
# Modeli kurduk.

model = lm.fit()

In [18]:
# Modelin özetlerini inceliyoruz (R-squared (Bağımsızlar bağımlıyı %98 oranda açıklamış) , adj r-squared (r kare değerinin düzeltilmiş hali) , 
# f-statistic (modelin anlamlılığını test etmek için) !!!!! , prob (0.05'ten küçük olduğu için anlamlı) !!!)

# (Alttaki tablo -> coef (kurulacak modeldeki katsayılar) !!!! , t ve P>|t| (elimizdeki katsayının anlamlı mı olduğunu anlamak için))
   
# coef'i , f-statistic yorumlamak , prob'u yorumlamak veya nihai olarak model denklemini yazmak önemli      !!!!!!!!!!!!!!!
# coef yorumlaması -> TV için 1 birim harcama (yatırım) yaparasam satışlarda ortalama 0.0538 artış olabilir anlamına gelir.     !!!!!!!!!!!!!!!!!!!

model.summary()


print("R-squared:", model.rsquared)
print("Adjusted R-squared:", model.rsquared_adj)
print("Adjusted R-squared:", model.f1_score)

Coefficients:
 TV           0.053792
radio        0.222227
newspaper    0.016816
dtype: float64
P-values:
 TV           1.778939e-97
radio        2.620210e-59
newspaper    1.263266e-02
dtype: float64
R-squared: 0.9819180990604569
Adjusted R-squared: 0.9816427401629004

# Scikit Learn İle Model Kurmak (Genelde bu yöntemi kullanacağız)

In [10]:
from sklearn.linear_model import LinearRegression

lm = LinearRegression()     # modeli oluşturduk
model = lm.fit(x , y)       # modeli çalıştırdık

In [11]:
model.intercept_    # b0

array([2.93888937])

In [12]:
model.coef_     # b1 , b2 , b3      # üstteki tablodakinden farklı olmasının sebebi ilgili kütüphanelerin kullandığı parametre tahmin yöntemleri

array([[ 0.04576465,  0.18853002, -0.00103749]])

# TAHMİN

- Sales = 2.94 + Tv * 0.04 + radio * 0.19 - newspaper * 0.001

In [13]:
# 30 birim TV , 10 birim radio , 40 birim gazete harcaması olsun. Bu durmda ne kadarlık bir satış beklenir?
# El yordamıyla bulunması:

2.94 + 30 * 0.04 + 10 * 0.19 - 40 * 0.001

5.999999999999999

In [14]:
# Model Aracılığıyla Bulunması:

import pandas as pd

yeni_veri = [[30] , [10] , [40]]
yeni_veri = pd.DataFrame(yeni_veri).T       # Transpozunu aldık çünkü değikenler satır bazında sıralanmış Tv radio np
                                            #                                                             30  10   40
model.predict(yeni_veri)

C:\Users\Bedirhan Örseloğlu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[6.15562918]])

# MODEL BAŞARISINI DEĞERLENDİRME

In [15]:
y.head(10)   # gerçek değerler

   sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9
5    7.2
6   11.8
7   13.2
8    4.8
9   10.6

In [16]:
a = model.predict(x)[0:10]  # tahmini değerler
a = pd.DataFrame(a)
a

           0
0  20.523974
1  12.337855
2  12.307671
3  17.597830
4  13.188672
5  12.478348
6  11.729760
7  12.122953
8   3.727341
9  12.550849

In [17]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y , model.predict(x))        # hata kareler ortalamamızı (MSE) bulduk.
MSE

2.784126314510936

In [18]:
import numpy as np

RMSE = np.sqrt(MSE)     # RMSE oranımızı bulduk.
RMSE

1.6685701407225697

# MODEL TUNING (Doğrulama)

In [19]:
x.head()

      TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [20]:
y.head()

   sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

    Hold Out Yöntemi:

In [21]:

from sklearn.model_selection import train_test_split

# Veri setimizi eğitim ve test setlerine ayırıyoruz.
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2 , random_state=99)     # test size = %80 eğitim %20 eğitim seti olsun ; random state = her çalıştırdığımda farklı sonuç olmasın
                                                                                                    #                                                veri seti içindeki hangi 20'ye 80 alınacak

In [22]:
# Eğitim setinin bağımsız değişkenleri

x_train.head()

        TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [23]:
# Eğitim setinin bağımlı değişkenleri

y_train.head()

     sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [24]:
# Test setinin bağımsız değişkenleri

x_test.head()

       TV  radio  newspaper
135  48.3   47.0        8.5
127  80.2    0.0        9.2
191  75.5   10.8        6.0
66   31.5   24.6        2.2
119  19.4   16.0       22.3

In [25]:
# Test setinin bağımlı değişkenleri

y_test.head()

     sales
135   11.6
127    8.8
191    9.9
66     9.5
119    6.6

In [26]:
lm = LinearRegression()

model = lm.fit(x_train , y_train)
np.sqrt(mean_squared_error(y_train , model.predict(x_train)))       # Bu hata eğitim hata oranımız

1.7236824822650751

In [27]:
np.sqrt(mean_squared_error(y_test , model.predict(x_test)))       # Bu hata test hata oranımız

1.4312783138301641

    K-Katlı Çapraz Doğrulama Yöntemi:

 - Hold Out Yönteminde random_state'i değiştirdiğimizde farklı sonuçlar elde ediyoruz. Çünkü %20'ye %80 ayırırken hangi veriler alındığı random olarak seçiliyor ve buna bağlı olarak sonuç değişiyor. İşte bu durumdan kaynaklanan bir hata almamak için K-Katlı Çapraz Doğrulama Yöntemini kullanıyoruz.

In [29]:
from sklearn.model_selection import cross_val_score

# Eğitim seti üzerinden 10 tane farklı hata hesapladık. Yani train seti kendi içinde 10 farklı parçaya bölündü. 9 parçayla önce model kurulup dışarıda kalan bir parça tahmin edildi. Ve bu her parça için tekrarlandı
cross_val_score(model , x_train , y_train , cv=10 , scoring="neg_mean_squared_error")       # cv = cross validation (çapraz doğrulama)

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [33]:
# Üstteki hataların pozitifini ve ortalamasını alıyoruz
# Yani eğitim setine ilişkin ortalama hatamızı bulduk

print(np.mean(-cross_val_score(model , x_train , y_train , cv=10 , scoring="neg_mean_squared_error")))

print("RMSE Değeri" , np.sqrt(np.mean(-cross_val_score(model , x_train , y_train , cv=10 , scoring="neg_mean_squared_error"))))

3.3170289742341255
RMSE Değeri 1.8212712522395245

In [36]:
# Bu işlem sadece tek başına test ve eğitimin vermişi olduğu hata oranından daha doğru bir hata oranı veriyor. Dolayısıyla hata oranlarını karşılaştırmak için bu işlemi uyguladık.
# Bu bize doğrulanmış hata oranını verir.

np.sqrt(np.mean(-cross_val_score(model , x , y , cv=10 , scoring="neg_mean_squared_error")))     # x ve y yazdık direkt !!!!!!!

1.749276312684338